"""Serialize a ReceiverConfig to GNSS-SDR .conf text.

Sections ordered GNSS-SDR globals -> SignalSource -> Conditioner ->
Channels -> Acquisition -> Tracking -> TelemetryDecoder -> Observables ->
PVT, matching the conventional layout of the upstream example configs.
"""

from __future__ import annotations

from gnss_sdr_configurator import __version__
from gnss_sdr_configurator.model.config import ReceiverConfig

SECTION_ORDER = [
    "GNSS-SDR",
    "SignalSource",
    "SignalConditioner",
    "DataTypeAdapter",
    "InputFilter",
    "Resampler",
    "Channels",
    "Channel",
    "Acquisition",
    "Tracking",
    "TelemetryDecoder",
    "Observables",
    "PVT",
]


def _section(key: str) -> str:
    """Section a fully-qualified key belongs to: the block-role prefix
    without any per-signal/per-index suffix (Acquisition_1C -> Acquisition,
    Channels_1C -> Channels, SignalSource2 -> SignalSource)."""
    prefix = key.split(".", 1)[0]
    if prefix == "GNSS-SDR":
        return prefix
    base = prefix.split("_", 1)[0]
    return base.rstrip("0123456789")


def _sort_rank(key: str) -> tuple[int, str, str]:
    section = _section(key)
    try:
        section_rank = SECTION_ORDER.index(section)
    except ValueError:
        section_rank = len(SECTION_ORDER)
    prefix, _, param = key.partition(".")
    # implementation first within its block, then alphabetical
    param_rank = "" if param == "implementation" else param
    return (section_rank, prefix, param_rank)


def write_conf(config: ReceiverConfig, generated_from: str) -> str:
    """Render the config as .conf text (the caller writes it to disk)."""
    lines = [
        f"; Generated by gnss-sdr-configurator {__version__}",
        f"; Parameter schema extracted from GNSS-SDR commit {generated_from}",
        "",
        "[GNSS-SDR]",
        "",
    ]
    current_section = None
    for key, value in sorted(config.items(), key=lambda kv: _sort_rank(kv[0])):
        section = _section(key)
        if section != current_section:
            if current_section is not None:
                lines.append("")
            current_section = section
        lines.append(f"{key}={value}")
    lines.append("")
    return "\n".join(lines)
